"""
# CONTNUAR A LOGICA DE AVALIAÇÃO DE DUPLICIDADES
-> ok
# AINDA PRECISA LIGAR AS FUNÇÕES AO EVENTO DE ENTRADA
-> ok
# PROGRAMAR A ALTERAÇÕ VISUAL PARA A CELULA ALTERADA
-> ok
# 
# PROGRAMAR ALTERAÇÃO VISUAL DA LINHA , COLUNA E QUADRANTE DA CELULA SELECIONADA.
# CELULA MAIS ESCURA QUE LINHA, COLUNA E QUADRANTE
# FUNCAO DEVE APLICAR A COR EM TODAS AS CELULAS PARA O PADRAO E DEPOIS ALTERAR PARA A SELECAO
"""

#VIDEO TUTORIAL PARA MONTAGEM DE INTERFACE GRAFICA
# https://www.youtube.com/watch?v=9iZLDnW_vwU&t=908s

# TABELA DE CORES
# https://celke.com.br/artigo/tabela-de-cores-html-nome-hexadecimal-rgb
